# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='todo.proto',
  package='main',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntodo.proto\x12\x04main\"\x10\n\x02id\x12\n\n\x02id\x18\x01 \x01(\x03\"!\n\x04todo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\t\"\"\n\x05todos\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.main.todo\"\x1e\n\ttodoValue\x12\x11\n\ttodoValue\x18\x01 \x01(\t\"\x07\n\x05\x65mpty2\xa1\x01\n\x03\x61pi\x12&\n\x07\x61\x64\x64Todo\x12\x0f.main.todoValue\x1a\n.main.todo\x12&\n\x07getTodo\x12\x0f.main.todoValue\x1a\n.main.todo\x12\"\n\x06getAll\x12\x0b.main.empty\x1a\x0b.main.todos\x12&\n\x07\x64\x65lTodo\x12\x0f.main.todoValue\x1a\n.main.todob\x06proto3')
)




_ID = _descriptor.Descriptor(
  name='id',
  full_name='main.id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='main.id.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=36,
)


_TODO = _descriptor.Descriptor(
  name='todo',
  full_name='main.todo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='main.todo.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='main.todo.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=71,
)


_TODOS = _descriptor.Descriptor(
  name='todos',
  full_name='main.todos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todos', full_name='main.todos.todos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=107,
)


_TODOVALUE = _descriptor.Descriptor(
  name='todoValue',
  full_name='main.todoValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todoValue', full_name='main.todoValue.todoValue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=139,
)


_EMPTY = _descriptor.Descriptor(
  name='empty',
  full_name='main.empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=148,
)

_TODOS.fields_by_name['todos'].message_type = _TODO
DESCRIPTOR.message_types_by_name['id'] = _ID
DESCRIPTOR.message_types_by_name['todo'] = _TODO
DESCRIPTOR.message_types_by_name['todos'] = _TODOS
DESCRIPTOR.message_types_by_name['todoValue'] = _TODOVALUE
DESCRIPTOR.message_types_by_name['empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

id = _reflection.GeneratedProtocolMessageType('id', (_message.Message,), dict(
  DESCRIPTOR = _ID,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:main.id)
  ))
_sym_db.RegisterMessage(id)

todo = _reflection.GeneratedProtocolMessageType('todo', (_message.Message,), dict(
  DESCRIPTOR = _TODO,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:main.todo)
  ))
_sym_db.RegisterMessage(todo)

todos = _reflection.GeneratedProtocolMessageType('todos', (_message.Message,), dict(
  DESCRIPTOR = _TODOS,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:main.todos)
  ))
_sym_db.RegisterMessage(todos)

todoValue = _reflection.GeneratedProtocolMessageType('todoValue', (_message.Message,), dict(
  DESCRIPTOR = _TODOVALUE,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:main.todoValue)
  ))
_sym_db.RegisterMessage(todoValue)

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:main.empty)
  ))
_sym_db.RegisterMessage(empty)



_API = _descriptor.ServiceDescriptor(
  name='api',
  full_name='main.api',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=151,
  serialized_end=312,
  methods=[
  _descriptor.MethodDescriptor(
    name='addTodo',
    full_name='main.api.addTodo',
    index=0,
    containing_service=None,
    input_type=_TODOVALUE,
    output_type=_TODO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getTodo',
    full_name='main.api.getTodo',
    index=1,
    containing_service=None,
    input_type=_TODOVALUE,
    output_type=_TODO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getAll',
    full_name='main.api.getAll',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TODOS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='delTodo',
    full_name='main.api.delTodo',
    index=3,
    containing_service=None,
    input_type=_TODOVALUE,
    output_type=_TODO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_API)

DESCRIPTOR.services_by_name['api'] = _API

# @@protoc_insertion_point(module_scope)
