# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import todo_pb2 as todo__pb2


class apiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.addTodo = channel.unary_unary(
        '/main.api/addTodo',
        request_serializer=todo__pb2.todoValue.SerializeToString,
        response_deserializer=todo__pb2.todo.FromString,
        )
    self.getTodo = channel.unary_unary(
        '/main.api/getTodo',
        request_serializer=todo__pb2.todoValue.SerializeToString,
        response_deserializer=todo__pb2.todo.FromString,
        )
    self.getAll = channel.unary_unary(
        '/main.api/getAll',
        request_serializer=todo__pb2.empty.SerializeToString,
        response_deserializer=todo__pb2.todos.FromString,
        )
    self.delTodo = channel.unary_unary(
        '/main.api/delTodo',
        request_serializer=todo__pb2.todoValue.SerializeToString,
        response_deserializer=todo__pb2.todo.FromString,
        )


class apiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def addTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_apiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'addTodo': grpc.unary_unary_rpc_method_handler(
          servicer.addTodo,
          request_deserializer=todo__pb2.todoValue.FromString,
          response_serializer=todo__pb2.todo.SerializeToString,
      ),
      'getTodo': grpc.unary_unary_rpc_method_handler(
          servicer.getTodo,
          request_deserializer=todo__pb2.todoValue.FromString,
          response_serializer=todo__pb2.todo.SerializeToString,
      ),
      'getAll': grpc.unary_unary_rpc_method_handler(
          servicer.getAll,
          request_deserializer=todo__pb2.empty.FromString,
          response_serializer=todo__pb2.todos.SerializeToString,
      ),
      'delTodo': grpc.unary_unary_rpc_method_handler(
          servicer.delTodo,
          request_deserializer=todo__pb2.todoValue.FromString,
          response_serializer=todo__pb2.todo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'main.api', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
